"""
Event definitions for the Enterprise AI Router and Intelligence Orchestrator.
These events can be subscribed to by any monitoring, analytics, or UI streaming modules.
"""

# Event Constants
ROUTER_USER_MESSAGE_RECEIVED = "USER_MESSAGE_RECEIVED"
ROUTER_MEMORY_RETRIEVED = "MEMORY_RETRIEVED"
ROUTER_INTENT_CLASSIFIED = "INTENT_CLASSIFIED"
ROUTER_PLAN_GENERATED = "PLAN_GENERATED"
ROUTER_MODULE_STARTED = "MODULE_STARTED"
ROUTER_MODULE_COMPLETED = "MODULE_COMPLETED"
ROUTER_MODULE_FAILED = "MODULE_FAILED"
ROUTER_RESPONSE_GENERATED = "RESPONSE_GENERATED"
